# Dependabot configuration for edi-partner-configs
# This repository contains partner configuration files and validation schemas

version: 2

updates:
  # GitHub Actions workflow dependencies (for validation workflows)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "02:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "edi-platform-team"
    labels:
      - "dependencies"
      - "config"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    rebase-strategy: "auto"

  # npm packages for JSON schema validation tools (if applicable)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "02:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "edi-platform-team"
    labels:
      - "dependencies"
      - "config"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    rebase-strategy: "auto"
    ignore:
      # Ignore major version updates for manual review
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
